# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='commands.proto',
  package='bismuth',
  syntax='proto2',
  serialized_pb=_b('\n\x0e\x63ommands.proto\x12\x07\x62ismuth\"\x19\n\x02TX\x12\x13\n\x0bint32_value\x18\x01 \x01(\x05\"D\n\x02IP\x12\x0c\n\x04ipv4\x18\x01 \x02(\r\x12\r\n\x05ipv6a\x18\x02 \x01(\x04\x12\r\n\x05ipv6b\x18\x03 \x01(\x04\x12\x12\n\x04port\x18\x04 \x01(\r:\x04\x35\x36\x35\x38\"\xe2\x01\n\x07\x43ommand\x12&\n\x07\x63ommand\x18\x01 \x02(\x0e\x32\x15.bismuth.Command.Type\x12\x16\n\x0cstring_value\x18\x02 \x01(\tH\x00\x12\x15\n\x0bint32_value\x18\x03 \x01(\x05H\x00\x12\x18\n\x03txs\x18\x05 \x03(\x0b\x32\x0b.bismuth.TX\x12\x18\n\x03ips\x18\x06 \x03(\x0b\x32\x0b.bismuth.IP\"C\n\x04Type\x12\t\n\x05hello\x10\x00\x12\x06\n\x02ok\x10\x01\x12\x06\n\x02ko\x10\x02\x12\x08\n\x04ping\x10\x03\x12\t\n\x05peers\x10\x04\x12\x0b\n\x07message\x10\nB\x07\n\x05param*{\n\tko_reason\x12\r\n\tno_reason\x10\x00\x12\x14\n\x10version_mismatch\x10\x01\x12\n\n\x06\x62\x61\x64_ip\x10\x02\x12\x0e\n\nbad_pubkey\x10\x03\x12\r\n\tbad_block\x10\x04\x12\x0c\n\x08\x62\x61\x64_slot\x10\x05\x12\x10\n\x0cno_resources\x10\x06')
)

_KO_REASON = _descriptor.EnumDescriptor(
  name='ko_reason',
  full_name='bismuth.ko_reason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='no_reason', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='version_mismatch', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bad_ip', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bad_pubkey', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bad_block', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bad_slot', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='no_resources', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=353,
  serialized_end=476,
)
_sym_db.RegisterEnumDescriptor(_KO_REASON)

ko_reason = enum_type_wrapper.EnumTypeWrapper(_KO_REASON)
no_reason = 0
version_mismatch = 1
bad_ip = 2
bad_pubkey = 3
bad_block = 4
bad_slot = 5
no_resources = 6


_COMMAND_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='bismuth.Command.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='hello', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ok', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ko', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ping', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='peers', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='message', index=5, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=275,
  serialized_end=342,
)
_sym_db.RegisterEnumDescriptor(_COMMAND_TYPE)


_TX = _descriptor.Descriptor(
  name='TX',
  full_name='bismuth.TX',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int32_value', full_name='bismuth.TX.int32_value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=52,
)


_IP = _descriptor.Descriptor(
  name='IP',
  full_name='bismuth.IP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ipv4', full_name='bismuth.IP.ipv4', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipv6a', full_name='bismuth.IP.ipv6a', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipv6b', full_name='bismuth.IP.ipv6b', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='bismuth.IP.port', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=5658,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=122,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='bismuth.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='bismuth.Command.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='bismuth.Command.string_value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int32_value', full_name='bismuth.Command.int32_value', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='txs', full_name='bismuth.Command.txs', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ips', full_name='bismuth.Command.ips', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMAND_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='param', full_name='bismuth.Command.param',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=125,
  serialized_end=351,
)

_COMMAND.fields_by_name['command'].enum_type = _COMMAND_TYPE
_COMMAND.fields_by_name['txs'].message_type = _TX
_COMMAND.fields_by_name['ips'].message_type = _IP
_COMMAND_TYPE.containing_type = _COMMAND
_COMMAND.oneofs_by_name['param'].fields.append(
  _COMMAND.fields_by_name['string_value'])
_COMMAND.fields_by_name['string_value'].containing_oneof = _COMMAND.oneofs_by_name['param']
_COMMAND.oneofs_by_name['param'].fields.append(
  _COMMAND.fields_by_name['int32_value'])
_COMMAND.fields_by_name['int32_value'].containing_oneof = _COMMAND.oneofs_by_name['param']
DESCRIPTOR.message_types_by_name['TX'] = _TX
DESCRIPTOR.message_types_by_name['IP'] = _IP
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.enum_types_by_name['ko_reason'] = _KO_REASON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TX = _reflection.GeneratedProtocolMessageType('TX', (_message.Message,), dict(
  DESCRIPTOR = _TX,
  __module__ = 'commands_pb2'
  # @@protoc_insertion_point(class_scope:bismuth.TX)
  ))
_sym_db.RegisterMessage(TX)

IP = _reflection.GeneratedProtocolMessageType('IP', (_message.Message,), dict(
  DESCRIPTOR = _IP,
  __module__ = 'commands_pb2'
  # @@protoc_insertion_point(class_scope:bismuth.IP)
  ))
_sym_db.RegisterMessage(IP)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'commands_pb2'
  # @@protoc_insertion_point(class_scope:bismuth.Command)
  ))
_sym_db.RegisterMessage(Command)


# @@protoc_insertion_point(module_scope)
